# Generated by Django 5.2.8 on 2025-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='console_logs',
            field=models.TextField(blank=True, null=True, verbose_name='Логи консоли'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='js_errors',
            field=models.TextField(blank=True, null=True, verbose_name='JS-ошибки'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='network_errors',
            field=models.TextField(blank=True, null=True, verbose_name='Сетевые ошибки'),
        ),
    ]
